spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwellery_db
    username: root
    password: Princemitt@l26
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: jwellery-ecommerce

server:
  port: 9090
  servlet:
    context-path: /jwellery-ecommerce
application:
  config:
    trace: true