spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jewellery_db
    username: root
    password: root
<<<<<<< HEAD
    hikari:
      idle-timeout: 30000
      leak-detection-threshold: 2000
      connection-timeout: 30000
      maximum-pool-size: 5
=======
>>>>>>> 184eeb7cd7815dd1fa7fcfccda09a27010c6e24f
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: jewellery-ecommerce
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: singhtuski8102@gmail.com
      password: xuxb umjz gmwj tmxr
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
server:
  port: 9090
  servlet:
    context-path: /jewellery-ecommerce
application:
  config:
    trace: true

aws:
  access-key-id: AKIAVY2PHDFITEMWN5UB
  secret-access-key: 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
  bucket: jewellery-bucket
  region: ap-south-1
  stack:
    auto: false
jwt:
  tokenValidityInSeconds: 2160000 #200 hours

